name: Deploy Next.js to DO Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd portfolio-frontend
          npm install

      - name: Build Next.js
        run: |
          cd portfolio-frontend
          npm run build

      - name: Copy files to Droplet
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          source: |
            portfolio-frontend/.next
            portfolio-frontend/package.json
            portfolio-frontend/package-lock.json
            portfolio-frontend/node_modules
          target: "/var/www/devspark"
          exclude: |
            .git
            .github
            README.md
            wordpress
            tests
            docs

      - name: SSH & Restart PM2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/devspark
            npm install --production
            pm2 restart devspark-next || pm2 start npm --name devspark-next -- start
